### Site metadata ###

site_name: Algoritmekader concept
site_description: Concept van het algoritmekader. Het doel daarvan is om overheden op praktische wijze te ondersteunen, zodat zij op een wettige en ethisch verantwoorde wijze algoritmes en AI-systemen gebruiken.

### Build settings ###

theme: bootstrap

nav:
    - Home: index.md
  
repo_url: https://github.com/MinBZK/Algoritmekader